version: "3.9"

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "${N8N_PORT}:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${N8N_PORT}
      - N8N_PROTOCOL=${N8N_PROTOCOL}
    volumes:
      - ./data:/home/node/.n8n
    restart: always

  playwright:
    image: node:18
    container_name: playwright
    ports:
      - "8000:8000"
    volumes:
      - ./playwright:/usr/src/app
    working_dir: /usr/src/app
    command: ["/bin/sh", "-c", "npm install && npm start"]
    networks:
      - default
    restart: always
